services:
  - type: web
    name: bikefight
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: /

disk:
  - name: data
    mountPath: /data
    sizeGB: 1 