# render.yaml - A Blueprint for deploying the bikefight service

services:
  # This is the web service definition
  - type: web
    name: bikefight
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: /
  disk:
    - name: data
      mountPath: /data
      sizeGB: 1 